package com.shareIt.subject.application.convert;



import com.shareIt.domain.entity.SubjectInfoBO;
import com.shareIt.subject.application.dto.SubjectInfoDTO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import java.util.List;

/**
 * Subject Info DTO Converter
 *
 * This interface defines methods for converting between SubjectInfoDTO and SubjectInfoBO.
 * It is used to map data between the presentation layer (DTO) and business layer (BO).
 *
 * @author Liu Tongxun
 * @date 2025/06/01
 */
@Mapper
public interface SubjectInfoDTOConverter {

    // Singleton instance automatically generated by MapStruct
    SubjectInfoDTOConverter INSTANCE = Mappers.getMapper(SubjectInfoDTOConverter.class);

    /**
     * Convert SubjectInfoDTO (Data Transfer Object) to SubjectInfoBO (Business Object)
     *
     * @param subjectInfoDTO The DTO to be converted
     * @return The corresponding BO
     */
    SubjectInfoBO convertDTOToBO(SubjectInfoDTO subjectInfoDTO);

    /**
     * Convert SubjectInfoBO (Business Object) to SubjectInfoDTO (Data Transfer Object)
     *
     * @param subjectInfoBO The BO to be converted
     * @return The corresponding DTO
     */
    SubjectInfoDTO convertBOToDTO(SubjectInfoBO subjectInfoBO);

    /**
     * Convert a list of SubjectInfoBO objects to a list of SubjectInfoDTOs
     *
     * @param subjectInfoBO List of business objects
     * @return List of corresponding DTOs
     */
    List<SubjectInfoDTO> convertBOToDTOList(List<SubjectInfoBO> subjectInfoBO);
}
