package com.shareIt.subject.application.convert;


import com.shareIt.domain.entity.SubjectAnswerBO;
import com.shareIt.subject.application.dto.SubjectAnswerDTO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import java.util.List;

/**
 * Subject Answer DTO Converter
 *
 * This interface provides methods for converting between SubjectAnswerDTO and SubjectAnswerBO,
 * enabling data mapping between the presentation and business layers.
 *
 * @author Liu Tongxun
 * @date 2025/06/01
 */
@Mapper
public interface SubjectAnswerDTOConverter {

    // Singleton instance automatically generated by MapStruct
    SubjectAnswerDTOConverter INSTANCE = Mappers.getMapper(SubjectAnswerDTOConverter.class);

    /**
     * Convert SubjectAnswerDTO (Data Transfer Object) to SubjectAnswerBO (Business Object)
     *
     * @param subjectAnswerDTO The DTO to be converted
     * @return The corresponding BO
     */
    SubjectAnswerBO convertDTOToBO(SubjectAnswerDTO subjectAnswerDTO);

    /**
     * Convert a list of SubjectAnswerDTOs to a list of SubjectAnswerBOs
     *
     * @param dtoList List of DTOs to be converted
     * @return List of corresponding BOs
     */
    List<SubjectAnswerBO> convertListDTOToBO(List<SubjectAnswerDTO> dtoList);
}
