package com.shareIt.domain.convert;


import com.shareIt.domain.entity.SubjectInfoBO;
import com.shareIt.subject.infra.basic.entity.SubjectInfo;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import java.util.List;

/**
 * Subject Info Converter Interface
 *
 * Used to convert between different object types (such as entity and business objects),
 * facilitating data transfer and transformation between layers.
 *
 * Author: Liu Tongxun
 * Date: 2025/06/01
 */
@Mapper
public interface SubjectInfoConverter {

    // Singleton instance generated by MapStruct
    SubjectInfoConverter INSTANCE = Mappers.getMapper(SubjectInfoConverter.class);

    /**
     * Convert SubjectInfoBO (business object) to SubjectInfo (entity object)
     *
     * @param subjectInfoBO Business object representing subject information
     * @return Entity object representing subject information
     */
    SubjectInfo convertBoToInfo(SubjectInfoBO subjectInfoBO);

    List<SubjectInfoBO> convertListInfoToBO(List<SubjectInfo> subjectInfoList);
}
